version: '3.8'

services:
  voice-memos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: voice-memos-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
